# Name of workflow
name: Production build

# When workflow is triggered
on:
  pull_request:
    branches:
      - main

# Jobs to carry out
jobs:
  build_and_deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v2

      # Trigger Netlify build
      - name: Trigger Netlify build
        run: curl -X POST -d {} "https://api.netlify.com/build_hooks/your_production_build_hook_id"
